version: '2'
services:
  kafka:
    container_name: kafka
    image: spotify/kafka
    environment:
      ADVERTISED_PORT: 9092
    expose:
      - 9092
      - 2181
    ports:
      - 9092:9092
      - 2181:2181
    networks:
      - my-sample-network
    logging:
      driver: json-file
  message-producer:
    container_name: message-producer
    image: mdstech/message-producer
    environment:
      kafka.url: http://kafka:9092
    expose:
      - 8080
    ports:
      - 8081:8080
    networks:
      - my-sample-network
    links:
      - kafka
    depends_on:
      - kafka
    logging:
      driver: json-file
  message-consumer:
    container_name: message-consumer
    image: mdstech/message-consumer
    environment:
      kafka.url: http://kafka:9092
    expose:
      - 8080
    ports:
      - 8082:8080
    networks:
      - my-sample-network
    links:
      - kafka
    depends_on:
      - kafka
    logging:
      driver: json-file
  bulk-message-processor:
    container_name: bulk-message-processor
    image: mdstech/bulk-message-processor
    environment:
      http.producer.host: message-producer
      http.producer.port: 8080
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - my-sample-network
    links:
      - message-producer
    depends_on:
      - message-producer
    logging:
      driver: json-file

networks:
  my-sample-network:
    driver: bridge

